name: HeadSpace
favicon: null
layout_spectrum: 0.24707
typography_spectrum: 0.78643
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#997b60'
    - '#6d5144'
    - '#423122'
    - '#c5ab7e'
  brandStrength: 0.5
  lightness: 0.6475064610131085
  saturation: 0.42668065265752375
  rhythmicContrast: 0.42725565657019615
purpose: []
